# Generated by Django 4.1.7 on 2023-03-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='imagen',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
